# Generated by Django 5.1.1 on 2024-12-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0012_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
